openapi: 3.0.0
info:
  title: E-Comm Backend.
  description: Pro BackEnd Node JS E-Comm Store
  version: 1.1.0
  contact:
    email: sujaywebdev@gmail.com
    url: "https://sujayweb.dev"

# servers:
#   - url: "http://localhost:4000/api/v1"
#     description: for local host - Secure
#   - url: "https://localhost:4000/api/v1"
#     description: for local host - Regular

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host - Secure
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token

    BearerAuth:
      type: http
      scheme: bearer

paths:
  /:
    get:
      tags:
        - Home
      summary: returns a greet message from E Comm Store
      responses:
        200:
          description: All Good API call success
          content:
            application/json:
              schema:
                type: string
                example: "myString"
        400:
          description: Bad Request
        500:
          description: internal server error